#!/bin/bash

conky -c $HOME/.config/conky/cpu &
conky -c $HOME/.config/conky/memory &
conky -c $HOME/.config/conky/video &
conky -c $HOME/.config/conky/system &
conky -c $HOME/.config.conky/calendar

exit 0
